import 'package:monie/features/notifications/domain/entities/notification.dart'
    as notification_entity;
import 'package:monie/features/notifications/domain/repositories/notification_repository.dart';

class CreateBudgetNotification {
  final NotificationRepository _repository;

  CreateBudgetNotification(this._repository);

  Future<void> call({
    required String userId,
    required String budgetName,
    required double amount,
    required double spentAmount,
    required double percentage,
  }) async {
    String title;
    String message;

    if (percentage >= 100) {
      title = 'Budget Exceeded!';
      message =
          'You have exceeded your budget for "$budgetName". Spent: \$${spentAmount.toStringAsFixed(2)} / \$${amount.toStringAsFixed(2)}';
    } else if (percentage >= 80) {
      title = 'Budget Alert: 80% Reached';
      message =
          'You have used 80% of your budget for "$budgetName". Spent: \$${spentAmount.toStringAsFixed(2)} / \$${amount.toStringAsFixed(2)}';
    } else if (percentage >= 50) {
      title = 'Budget Alert: 50% Reached';
      message =
          'You have used 50% of your budget for "$budgetName". Spent: \$${spentAmount.toStringAsFixed(2)} / \$${amount.toStringAsFixed(2)}';
    } else {
      return; // No notification needed for less than 50%
    }

    final notification = notification_entity.Notification(
      id: '', // Will be generated by the database
      userId: userId,
      amount: spentAmount,
      type: notification_entity.NotificationType.budgetAlert,
      title: title,
      message: message,
      isRead: false,
      createdAt: DateTime.now(),
    );

    await _repository.createNotification(notification);
  }
}
